#ifndef  ENUM_H
#define  ENUM_H

enum math { x, y, Ax, By, C0 };
enum ascii { BACKSPACE = 8, ENTER = 13, SPACE = 32, COMMA = 44, MINUS, DOT, ZERO = 48, ONE = 50, HELP = 104 };
enum colors { 
	BLACK, BLUE, GREEN, CYAN, RED, MAGENTA, BROWN,
	LIGHT_GREY, DARK_GREY, LIGHT_BLUE, LIGHT_GREEN, LIGHT_CYAN, LIGHT_RED, LIGHT_MAGENTA,
	YELLOW, WHITE
};
enum sizes { MAX_FRACTIONAL_DIGITS_LIMIT = 5, KEYS_SIZE = 8, MAX_INTEGER_DIGITS_LIMIT, HINTS_SIZE = 17};

#endif